### ISSUE TITLE
Given a dataset and a spek with a table schema, check that indicated columns are present.

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/fraisty#16]
Basic check that the input data and table schema have the same column names.  Essentially, is the table schema actually about the data set.  Error if the column names in the schema are not found in the data set.  Extraneous column names are fine.

**Comment by b-sheppard** [comment]
This may be useful for non-csv input that readr will return a tibble for. The header checks should catch the cases.

```
csv_str <- "header1,header2,header3\n1,2,3\n4,5,6\n7,8,9"
tmp_csv_path <- tempfile()
not_csv_str <- '{"key":"value"}'
tmp_not_csv_path <- tempfile()

setup({
  writeLines(csv_str, tmp_csv_path)
  writeLines(not_csv_str, tmp_not_csv_path)
})

teardown({
  unlink(tmp_csv_path)
  unlink(tmp_not_csv_path)
})
```
